base: &base
  adapter: sqlite3
  timeout: 5000

development:
  database: db/development.sqlite3
  <<: *base

test:
  adapter: postgresql
  database: pwp
  username: <%= Rails.application.secrets.POSTGRES_USERNAME %>
  password: <%= Rails.application.secrets.POSTGRES_PASSWD %>
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: false

private:
  database: db/private.sqlite3
  <<: *base

production:
  adapter: postgresql
  database: pwp
  username: <%= Rails.application.credentials.dig(:postgres, :USERNAME) %>
  password: <%= Rails.application.credentials.dig(:postgres, :PASSWD) %>
  pool: 5
  timeout: 5000
  encoding: utf8
  reconnect: false
