PWPUSH_COM: '1'
CRYPT_KEY: 'pTnkLUgEYV4ohsJaoX1v'
CRYPT_SALT: 'cXOlOgofQF89igg4VM2g'
POSTGRES_USERNAME: 'passpush'
POSTGRES_PASSWD: 'v9XawGOi0tc4cQvEQwhK'
SECRET_KEY_BASE: '8a9c92e1816394f7956f62201f5949f41ffe29d1d01e614fee83cb27778afc07'
EXPIRE_AFTER_TIME_DEFAULT: '1'
EXPIRE_AFTER_TIME_MAX: '28'
EXPIRE_AFTER_VIEWS_DEFAULT: '1'
EXPIRE_AFTER_VIEWS_MAX: '10'

